import fs from 'fs';
import path from 'path';

export interface PersistentProduct {
  id: string;
  sku: string;
  barcode: string;
  itemName: string;
  description?: string;
  costPrice: number;
  sellingPrice: number;
  status: 'ACTIVE' | 'DRAFT' | 'DISCONTINUED';
  vendorId: string;
  vendorEmail: string;
  categoryId?: string;
  categoryName?: string;
  uomId?: string;
  uomCode?: string;
  uomName?: string;
  createdAt: string;
  updatedAt: string;
}

const PRODUCTS_FILE = path.join(process.cwd(), '.data', 'vendor_products.json');

function ensureDirExists() {
  const dir = path.join(process.cwd(), '.data');
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
}

export function loadPersistentProducts(): Record<string, PersistentProduct> {
  ensureDirExists();
  const seedProducts = getSeedDemoProducts();
  try {
    if (fs.existsSync(PRODUCTS_FILE)) {
      const parsed = JSON.parse(fs.readFileSync(PRODUCTS_FILE, 'utf-8'));
      return { ...seedProducts, ...parsed };
    }
  } catch (e) {}
  return seedProducts;
}

export function savePersistentProducts(products: Record<string, PersistentProduct>) {
  ensureDirExists();
  try {
    fs.writeFileSync(PRODUCTS_FILE, JSON.stringify(products, null, 2), 'utf-8');
  } catch (e) {}
}

export function getSeedDemoProducts(): Record<string, PersistentProduct> {
  const now = new Date().toISOString();
  return {
    'item_01': {
      id: 'item_01',
      sku: 'LQ-SCN-00101',
      barcode: '9312345001015',
      itemName: 'Industrial Handheld Wireless Barcode Scanner 2D (HD-900)',
      description: 'Heavy-duty IP65 Bluetooth 2D barcode scanner for warehouse receiving and bin picking.',
      costPrice: 120.00,
      sellingPrice: 249.99,
      status: 'ACTIVE',
      vendorId: 'vnd_usr_vendor_01',
      vendorEmail: 'vendor@logiqon.com',
      categoryId: 'cat_hw_scn',
      categoryName: 'Barcode Scanners',
      uomId: 'uom_pcs',
      uomCode: 'PCS',
      uomName: 'Pieces',
      createdAt: now,
      updatedAt: now,
    },
    'item_02': {
      id: 'item_02',
      sku: 'LQ-PRT-00102',
      barcode: '9312345001022',
      itemName: 'Thermal Transfer Desktop Label Printer 300DPI (LogiPrint-30)',
      description: 'High-speed industrial thermal label printer with Ethernet, USB & Wi-Fi module.',
      costPrice: 310.00,
      sellingPrice: 599.00,
      status: 'ACTIVE',
      vendorId: 'vnd_usr_vendor_01',
      vendorEmail: 'vendor@logiqon.com',
      categoryId: 'cat_prt_dsk',
      categoryName: 'Desktop Printers',
      uomId: 'uom_pcs',
      uomCode: 'PCS',
      uomName: 'Pieces',
      createdAt: now,
      updatedAt: now,
    },
    'item_03': {
      id: 'item_03',
      sku: 'LQ-MOB-00103',
      barcode: '9312345001039',
      itemName: 'Rugged Touch Mobile Computer Android 13 (LogiPDA-X5)',
      description: 'Enterprise 5.5-inch rugged mobile terminal with 2D zebra scan engine & 4G SIM.',
      costPrice: 450.00,
      sellingPrice: 899.00,
      status: 'ACTIVE',
      vendorId: 'vnd_usr_vendor_01',
      vendorEmail: 'vendor@logiqon.com',
      categoryId: 'cat_hw_mob',
      categoryName: 'Mobile Computers',
      uomId: 'uom_pcs',
      uomCode: 'PCS',
      uomName: 'Pieces',
      createdAt: now,
      updatedAt: now,
    },
    'item_04': {
      id: 'item_04',
      sku: 'LQ-RFD-00104',
      barcode: '9312345001046',
      itemName: 'UHF RFID Smart Asset Labels (Pack of 100 Tags)',
      description: 'High-durability printable UHF RFID adhesive tags for pallet and container tracking.',
      costPrice: 45.00,
      sellingPrice: 89.00,
      status: 'ACTIVE',
      vendorId: 'vnd_usr_vendor_01',
      vendorEmail: 'vendor@logiqon.com',
      categoryId: 'cat_rfid_tags',
      categoryName: 'RFID Smart Labels & Tags',
      uomId: 'uom_pk',
      uomCode: 'PK',
      uomName: 'Pack of 100',
      createdAt: now,
      updatedAt: now,
    },
    'item_05': {
      id: 'item_05',
      sku: 'LQ-LBL-00105',
      barcode: '9312345001053',
      itemName: 'Direct Thermal Shipping Labels 100mm x 150mm (Roll of 500)',
      description: 'Premium permanent adhesive direct thermal freight labels for parcel dispatch.',
      costPrice: 12.50,
      sellingPrice: 24.90,
      status: 'ACTIVE',
      vendorId: 'vnd_usr_vendor_01',
      vendorEmail: 'vendor@logiqon.com',
      categoryId: 'cat_prt_lbl',
      categoryName: 'Barcode Labels & Ribbons',
      uomId: 'uom_box',
      uomCode: 'BOX',
      uomName: 'Box of 10',
      createdAt: now,
      updatedAt: now,
    },
    'item_06': {
      id: 'item_06',
      sku: 'LQ-RBN-00106',
      barcode: '9312345001060',
      itemName: 'Thermal Transfer Resin Ribbon 110mm x 300m Black',
      description: 'Smudge-resistant black resin ribbon for outdoor chemical and asset tags.',
      costPrice: 18.00,
      sellingPrice: 38.50,
      status: 'ACTIVE',
      vendorId: 'vnd_usr_vendor_01',
      vendorEmail: 'vendor@logiqon.com',
      categoryId: 'cat_prt_lbl',
      categoryName: 'Barcode Labels & Ribbons',
      uomId: 'uom_box',
      uomCode: 'BOX',
      uomName: 'Box of 10',
      createdAt: now,
      updatedAt: now,
    },
    'item_07': {
      id: 'item_07',
      sku: 'LQ-PLT-00107',
      barcode: '9312345001077',
      itemName: 'Heavy-Duty Rackable Plastic Pallet 1165mm x 1165mm Standard',
      description: 'Australian standard rackable plastic pallet with 1500kg dynamic rating.',
      costPrice: 85.00,
      sellingPrice: 149.00,
      status: 'ACTIVE',
      vendorId: 'vnd_usr_vendor_01',
      vendorEmail: 'vendor@logiqon.com',
      categoryId: 'cat_wh_plt',
      categoryName: 'Pallets & Storage',
      uomId: 'uom_pcs',
      uomCode: 'PCS',
      uomName: 'Pieces',
      createdAt: now,
      updatedAt: now,
    },
    'item_08': {
      id: 'item_08',
      sku: 'LQ-BIN-00108',
      barcode: '9312345001084',
      itemName: 'Retro-Reflective Aisle Location Barcode Sign Plate',
      description: 'Long-range retro-reflective barcode sign for overhead warehouse racking aisles.',
      costPrice: 15.00,
      sellingPrice: 29.00,
      status: 'ACTIVE',
      vendorId: 'vnd_usr_vendor_01',
      vendorEmail: 'vendor@logiqon.com',
      categoryId: 'cat_wh_bin',
      categoryName: 'Location & Bin Markers',
      uomId: 'uom_pcs',
      uomCode: 'PCS',
      uomName: 'Pieces',
      createdAt: now,
      updatedAt: now,
    },
    'item_09': {
      id: 'item_09',
      sku: 'LQ-RFD-00109',
      barcode: '9312345001091',
      itemName: 'Fixed 4-Port Overhead Portal RFID Reader (LogiGate-400)',
      description: 'Industrial 4-port UHF RFID reader for automatic dock door pallet scanning.',
      costPrice: 950.00,
      sellingPrice: 1850.00,
      status: 'ACTIVE',
      vendorId: 'vnd_usr_vendor_01',
      vendorEmail: 'vendor@logiqon.com',
      categoryId: 'cat_rfid_rdr',
      categoryName: 'RFID Fixed Readers',
      uomId: 'uom_pcs',
      uomCode: 'PCS',
      uomName: 'Pieces',
      createdAt: now,
      updatedAt: now,
    },
    'item_10': {
      id: 'item_10',
      sku: 'LQ-SCN-00110',
      barcode: '9312345001107',
      itemName: 'Fixed-Mount Industrial Barcode Scanner (LogiScan-FM200)',
      description: 'Conveyor belt high-speed barcode reader for automated package sortation.',
      costPrice: 620.00,
      sellingPrice: 1190.00,
      status: 'ACTIVE',
      vendorId: 'vnd_usr_vendor_01',
      vendorEmail: 'vendor@logiqon.com',
      categoryId: 'cat_hw_scn',
      categoryName: 'Barcode Scanners',
      uomId: 'uom_pcs',
      uomCode: 'PCS',
      uomName: 'Pieces',
      createdAt: now,
      updatedAt: now,
    },
    'item_11': {
      id: 'item_11',
      sku: 'LQ-PRT-00111',
      barcode: '9312345001114',
      itemName: '24/7 Industrial Heavy-Duty Thermal Printer (LogiPrint-HD6)',
      description: 'Heavy metal casing 6-inch wide industrial barcode label printer for manufacturing lines.',
      costPrice: 1250.00,
      sellingPrice: 2399.00,
      status: 'ACTIVE',
      vendorId: 'vnd_usr_vendor_01',
      vendorEmail: 'vendor@logiqon.com',
      categoryId: 'cat_prt_ind',
      categoryName: 'Industrial Printers',
      uomId: 'uom_pcs',
      uomCode: 'PCS',
      uomName: 'Pieces',
      createdAt: now,
      updatedAt: now,
    },
    'item_12': {
      id: 'item_12',
      sku: 'LQ-CAB-00112',
      barcode: '9312345001121',
      itemName: 'Shielded CAT6A Industrial Ethernet Patch Cable 5m',
      description: 'Heavy-duty PUR jacketed Ethernet cable for dock door readers and IP cameras.',
      costPrice: 9.50,
      sellingPrice: 19.90,
      status: 'ACTIVE',
      vendorId: 'vnd_usr_vendor_01',
      vendorEmail: 'vendor@logiqon.com',
      categoryId: 'cat_hw',
      categoryName: 'Industrial Hardware',
      uomId: 'uom_pcs',
      uomCode: 'PCS',
      uomName: 'Pieces',
      createdAt: now,
      updatedAt: now,
    },
    'item_13': {
      id: 'item_13',
      sku: 'LQ-TAG-00113',
      barcode: '9312345001138',
      itemName: 'On-Metal Anti-Interference UHF RFID Hard Tag',
      description: 'Encapsulated IP68 rugged RFID tag for metallic container and forklift tracking.',
      costPrice: 3.50,
      sellingPrice: 7.90,
      status: 'ACTIVE',
      vendorId: 'vnd_usr_vendor_01',
      vendorEmail: 'vendor@logiqon.com',
      categoryId: 'cat_rfid_tags',
      categoryName: 'RFID Smart Labels & Tags',
      uomId: 'uom_box',
      uomCode: 'BOX',
      uomName: 'Box of 10',
      createdAt: now,
      updatedAt: now,
    },
    'item_14': {
      id: 'item_14',
      sku: 'LQ-BIN-00114',
      barcode: '9312345001145',
      itemName: 'Self-Adhesive Vinyl Bin Location Labels (Roll of 1000)',
      description: 'Yellow high-contrast 2D Datamatrix bin barcodes for shelf edge marking.',
      costPrice: 22.00,
      sellingPrice: 45.00,
      status: 'ACTIVE',
      vendorId: 'vnd_usr_vendor_01',
      vendorEmail: 'vendor@logiqon.com',
      categoryId: 'cat_wh_bin',
      categoryName: 'Location & Bin Markers',
      uomId: 'uom_pk',
      uomCode: 'PK',
      uomName: 'Pack of 100',
      createdAt: now,
      updatedAt: now,
    },
    'item_15': {
      id: 'item_15',
      sku: 'LQ-MOB-00115',
      barcode: '9312345001152',
      itemName: 'Forklift-Mounted Vehicle Computer Terminal 10-inch (LogiTab-V10)',
      description: 'Vibration-resistant touchscreen vehicle computer with integrated power regulator.',
      costPrice: 1100.00,
      sellingPrice: 2150.00,
      status: 'ACTIVE',
      vendorId: 'vnd_usr_vendor_01',
      vendorEmail: 'vendor@logiqon.com',
      categoryId: 'cat_hw_mob',
      categoryName: 'Mobile Computers',
      uomId: 'uom_pcs',
      uomCode: 'PCS',
      uomName: 'Pieces',
      createdAt: now,
      updatedAt: now,
    },
    'item_16': {
      id: 'item_16',
      sku: 'LQ-SCN-00116',
      barcode: '9312345001169',
      itemName: 'Long-Range DPM Direct Part Mark Barcode Scanner (HD-950)',
      description: 'Specialized laser DPM scanner for etched serial numbers on automotive parts.',
      costPrice: 580.00,
      sellingPrice: 1120.00,
      status: 'ACTIVE',
      vendorId: 'vnd_usr_vendor_01',
      vendorEmail: 'vendor@logiqon.com',
      categoryId: 'cat_hw_scn',
      categoryName: 'Barcode Scanners',
      uomId: 'uom_pcs',
      uomCode: 'PCS',
      uomName: 'Pieces',
      createdAt: now,
      updatedAt: now,
    },
    'item_17': {
      id: 'item_17',
      sku: 'LQ-PRT-00117',
      barcode: '9312345001176',
      itemName: 'Mobile Belt-Clip Wireless Receipt & Label Printer (LogiGo-2)',
      description: 'Compact 2-inch Bluetooth mobile printer for cross-docking and markdown labelling.',
      costPrice: 190.00,
      sellingPrice: 380.00,
      status: 'ACTIVE',
      vendorId: 'vnd_usr_vendor_01',
      vendorEmail: 'vendor@logiqon.com',
      categoryId: 'cat_prt_dsk',
      categoryName: 'Desktop Printers',
      uomId: 'uom_pcs',
      uomCode: 'PCS',
      uomName: 'Pieces',
      createdAt: now,
      updatedAt: now,
    },
    'item_18': {
      id: 'item_18',
      sku: 'LQ-PLT-00118',
      barcode: '9312345001183',
      itemName: 'Clear Stretch Wrap Pallet Film 500mm x 450m (Carton of 4)',
      description: 'High-clarity cast stretch film for unitizing pallet loads for freight.',
      costPrice: 42.00,
      sellingPrice: 79.00,
      status: 'ACTIVE',
      vendorId: 'vnd_usr_vendor_01',
      vendorEmail: 'vendor@logiqon.com',
      categoryId: 'cat_wh_plt',
      categoryName: 'Pallets & Storage',
      uomId: 'uom_ctn',
      uomCode: 'CTN',
      uomName: 'Carton of 50',
      createdAt: now,
      updatedAt: now,
    },
    'item_19': {
      id: 'item_19',
      sku: 'LQ-RFD-00119',
      barcode: '9312345001190',
      itemName: 'High-Gain Circular Polarized RFID Antenna (9dBi)',
      description: 'Outdoor weatherproof RFID antenna for gate portals and warehouse conveyor belts.',
      costPrice: 180.00,
      sellingPrice: 340.00,
      status: 'ACTIVE',
      vendorId: 'vnd_usr_vendor_01',
      vendorEmail: 'vendor@logiqon.com',
      categoryId: 'cat_rfid_rdr',
      categoryName: 'RFID Fixed Readers',
      uomId: 'uom_pcs',
      uomCode: 'PCS',
      uomName: 'Pieces',
      createdAt: now,
      updatedAt: now,
    },
    'item_20': {
      id: 'item_20',
      sku: 'LQ-LBL-00120',
      barcode: '9312345001206',
      itemName: 'Polyester Synthetic Asset Tags 50mm x 25mm (Roll of 2000)',
      description: 'Tear-proof silver polyester barcodes resistant to oil, water, and solvents.',
      costPrice: 35.00,
      sellingPrice: 69.00,
      status: 'ACTIVE',
      vendorId: 'vnd_usr_vendor_01',
      vendorEmail: 'vendor@logiqon.com',
      categoryId: 'cat_prt_lbl',
      categoryName: 'Barcode Labels & Ribbons',
      uomId: 'uom_pk',
      uomCode: 'PK',
      uomName: 'Pack of 100',
      createdAt: now,
      updatedAt: now,
    },
    'item_21': {
      id: 'item_21',
      sku: 'LQ-SCN-00121',
      barcode: '9312345001213',
      itemName: 'Hands-Free Presentation Barcode Scanner 2D (Desktop Omnidirectional)',
      description: 'Hands-free presentation scanner for high-throughput retail checkout and packing stations.',
      costPrice: 140.00,
      sellingPrice: 289.00,
      status: 'DRAFT',
      vendorId: 'vnd_usr_vendor_01',
      vendorEmail: 'vendor@logiqon.com',
      categoryId: 'cat_hw_scn',
      categoryName: 'Barcode Scanners',
      uomId: 'uom_pcs',
      uomCode: 'PCS',
      uomName: 'Pieces',
      createdAt: now,
      updatedAt: now,
    },
    'item_22': {
      id: 'item_22',
      sku: 'LQ-PRT-00122',
      barcode: '9312345001220',
      itemName: 'Printhead Replacement Kit 300DPI for Industrial Printer',
      description: 'Genuine thermal printhead replacement module for 300DPI LogiPrint industrial models.',
      costPrice: 280.00,
      sellingPrice: 490.00,
      status: 'DISCONTINUED',
      vendorId: 'vnd_usr_vendor_01',
      vendorEmail: 'vendor@logiqon.com',
      categoryId: 'cat_prt_ind',
      categoryName: 'Industrial Printers',
      uomId: 'uom_pcs',
      uomCode: 'PCS',
      uomName: 'Pieces',
      createdAt: now,
      updatedAt: now,
    },
  };
}
